//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeb1.Services {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.IFederatedService")]
    public interface IFederatedService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFederatedService/Ping", ReplyAction="http://tempuri.org/IFederatedService/PingResponse")]
        string Ping(string echo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFederatedService/Ping", ReplyAction="http://tempuri.org/IFederatedService/PingResponse")]
        System.Threading.Tasks.Task<string> PingAsync(string echo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFederatedServiceChannel : TestWeb1.Services.IFederatedService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FederatedServiceClient : System.ServiceModel.ClientBase<TestWeb1.Services.IFederatedService>, TestWeb1.Services.IFederatedService {
        
        public FederatedServiceClient() {
        }
        
        public FederatedServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FederatedServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FederatedServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FederatedServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Ping(string echo) {
            return base.Channel.Ping(echo);
        }
        
        public System.Threading.Tasks.Task<string> PingAsync(string echo) {
            return base.Channel.PingAsync(echo);
        }
    }
}
